 
version: '2'
services:
  web:
    container_name: Odoo-Demo
    #image: odoo:10.0
    build: ./Docker
    depends_on:
      - db
    command: -- --dev=reload
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./:/var/logs/odoo
      - ./addons:/mnt/extra-addons
      - ./:/opt/odoo/logs/
  db:
    container_name: OdooDB-Demo
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  odoo-web-data:
  odoo-db-data:
